export const WALLET_TYPES = {
  FIAT: 'FIAT',
  DEPOSIT: 'DEPOSIT',
  ROI: 'ROI',
  STAKING: 'STAKING',
  REWARD: 'REWARD',
  WITHDRAWAL: 'WITHDRAWAL'
};

export const WALLET_LABELS = {
  [WALLET_TYPES.FIAT]: 'Fiat Wallet',
  [WALLET_TYPES.DEPOSIT]: 'Deposit Wallet',
  [WALLET_TYPES.ROI]: 'ROI Wallet',
  [WALLET_TYPES.STAKING]: 'Staking Wallet',
  [WALLET_TYPES.REWARD]: 'Rewards Wallet',
  [WALLET_TYPES.WITHDRAWAL]: 'Withdrawal Wallet'
};

export const WALLET_COLORS = {
  [WALLET_TYPES.FIAT]: '#3B82F6', // Blue
  [WALLET_TYPES.DEPOSIT]: '#10B981', // Emerald
  [WALLET_TYPES.ROI]: '#8B5CF6', // Violet
  [WALLET_TYPES.STAKING]: '#F59E0B', // Amber
  [WALLET_TYPES.REWARD]: '#EC4899', // Pink
  [WALLET_TYPES.WITHDRAWAL]: '#6366F1' // Indigo
};

export const TRANSACTION_TYPES = {
  ROI: 'ROI',
  COMMISSION: 'COMMISSION',
  ROYALTY: 'ROYALTY',
  RANK_BONUS: 'RANK_BONUS',
  REWARDS: 'REWARDS',
  TRANSFER: 'TRANSFER',
  INVESTMENT: 'INVESTMENT',
  WITHDRAWAL: 'WITHDRAWAL',
  DEPOSIT: 'DEPOSIT'
};
